### ISSUE TITLE
[FEATURE] 좋아요, 댓글 시스템 제작

### ISSUE THREAD

**Issue by Baejw0111** [Baejw0111/Re-view#14]
## 기능 설명

리뷰에 유저들이 좋아요, 또는 댓글을 달 수 있다.

## TODO

 

- [x] DB 모델 설계
- [x] 좋아요 api 제작
- [x] 댓글 달기 api 제작
- [x] ui 상호작용 설계 및 제작
