### ISSUE TITLE
[FEATURE] 최적화

### ISSUE THREAD

**Issue by Baejw0111** [Baejw0111/Re-view#18]
## 기능 설명

- 서비스의 성능을 개선할 수 있는 작업

## TODO

 

- [x] 이미지 렌더링 최적화
- [x] 사용자가 업로드한 이미지 webp 확장자로 전환해 저장
- [x] react-query를 통한 api 요청 최적화
