### ISSUE TITLE
[FEATURE] 전반적인 디자인 요소 적용

### ISSUE THREAD

**Issue by Baejw0111** [Baejw0111/Re-view#23]
## 기능 설명

반응형 디자인, 토스트, 스켈레톤과 같은 서비스 전반적으로 적용되는 디자인들을 적용

## TODO

 

- [x] 에러 화면 통일
- [x] 반응형 디자인 적용
- [x] 스켈레톤 적용
- [x] 로고 디자인 및 적용
- [x] 토스트 기능 적용
