### ISSUE TITLE
[FEATURE] DB 구축

### ISSUE THREAD

**Issue by Baejw0111** [Baejw0111/Re-view#3]
## 기능 설명

MongoDB 서버 구축 후 테스트 API 제작해 연결 테스트하기

## 기대 효과

서비스에서 생성되는 데이터 관리 가능

## TODO

 

- [x] MongoDB 사용법 공부
- [x] MongoDB 서버 구축
- [x] 테스트 API 제작
